/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmpregadosRouteImport } from './routes/empregados'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as IndexRouteImport } from './routes/index'

const EmpregadosRoute = EmpregadosRouteImport.update({
  id: '/empregados',
  path: '/empregados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/dashboard': typeof DashboardRoute
  '/empregados': typeof EmpregadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/dashboard': typeof DashboardRoute
  '/empregados': typeof EmpregadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/dashboard': typeof DashboardRoute
  '/empregados': typeof EmpregadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checklists' | '/dashboard' | '/empregados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checklists' | '/dashboard' | '/empregados'
  id: '__root__' | '/' | '/checklists' | '/dashboard' | '/empregados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistsRoute: typeof ChecklistsRoute
  DashboardRoute: typeof DashboardRoute
  EmpregadosRoute: typeof EmpregadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/empregados': {
      id: '/empregados'
      path: '/empregados'
      fullPath: '/empregados'
      preLoaderRoute: typeof EmpregadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistsRoute: ChecklistsRoute,
  DashboardRoute: DashboardRoute,
  EmpregadosRoute: EmpregadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
